% INS_Model_Analysis.m
model = 'INS';  % 确保模型文件 INS.slx 在路径中

% 加载模型
load_system(model);

% 创建报告
import slreportgen.report.*
import slreportgen.dom.*

rpt = Report('INS_Model_Report', 'html');

% 添加封面页
add(rpt, TitlePage('Title', 'INS 模型分析报告', 'Author', 'Generated by MATLAB'));
add(rpt, TableOfContents);

% 添加模型图（主图）
mdlDiagram = ModelDiagram(model);
mdlDiagram.ScreenshotFormat = 'png';
add(rpt, Section('Title', '模型结构图', 'Content', mdlDiagram));

% 添加模块列表
blkList = ComponentSummary(model);
blkList.Title = '模块统计与列表';
add(rpt, blkList);

% 添加端口信息
portReport = PortTable(model);
add(rpt, Section('Title', '输入输出端口', 'Content', portReport));

% 添加模型配置参数
config = ConfigurationProperties(model);
config.Properties = {'SolverType', 'StopTime', 'FixedStep', 'PeriodicSampleTimes'};
add(rpt, Section('Title', '仿真配置', 'Content', config));

% 保存并关闭
close(rpt);

% 打开报告
rptview(rpt);